{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Clientes\",\"Pedidos\",\"Produtos\",\"Vendas\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "5327edaf-2a96-491f-a5cb-714bf0e8d6ef",
        "fromColumn": "Data Pedido",
        "fromTable": "Pedidos",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2f00db4d-7c5b-4fa3-b6fc-ae9547d2247c"
      },
      {
        "name": "8d4b3d60-a80e-4dc9-8795-69601627cdfd",
        "fromColumn": "Data Envio",
        "fromTable": "Pedidos",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_548a3cda-c5a8-44fa-ab34-87aa11109832"
      },
      {
        "name": "AutoDetected_1809eda2-4ae2-4153-8ceb-33a574bb1fd9",
        "fromColumn": "Cliente",
        "fromTable": "Vendas",
        "toColumn": "ID Cliente",
        "toTable": "Clientes"
      },
      {
        "name": "027742aa-5c50-4c80-a1f5-69e093fbbfeb",
        "fromColumn": "Produto",
        "fromTable": "Vendas",
        "toColumn": "ID Produto",
        "toTable": "Produtos"
      },
      {
        "name": "b2e02bd9-7c07-142f-cee4-d25ffd8b58ed",
        "fromColumn": "Pedido",
        "fromTable": "Vendas",
        "toColumn": "ID Pedido",
        "toTable": "Pedidos"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "Clientes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95fbd364-6f1b-4851-8010-a1143388e608",
            "sourceColumn": "ID Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Nome Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fcd0a075-2d44-4c43-a02c-55bf5b8db6f7",
            "sourceColumn": "Nome Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Segmento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d01dd34c-9eba-450f-be51-98c5a8f04ed0",
            "sourceColumn": "Segmento",
            "summarizeBy": "none"
          },
          {
            "name": "Cidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d5fe550-5480-4d60-a360-fec4336094b2",
            "sourceColumn": "Cidade",
            "summarizeBy": "none"
          },
          {
            "name": "Estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adb99da8-e41f-4442-8c4e-4c6c0f06a437",
            "sourceColumn": "Estado",
            "summarizeBy": "none"
          },
          {
            "name": "Pais",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4588519-b81b-4c43-8998-ddbb705c7ae8",
            "sourceColumn": "Pais",
            "summarizeBy": "none"
          },
          {
            "name": "Mercado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "545d89be-f9ef-41cc-9026-279b5bfd5820",
            "sourceColumn": "Mercado",
            "summarizeBy": "none"
          },
          {
            "name": "Regiao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "858755b8-9d9e-4ac3-9c7b-60cf48d0c76a",
            "sourceColumn": "Regiao",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "eb3eabba-1a88-42c4-87ef-baf78e5cc1f2",
        "partitions": [
          {
            "name": "Clientes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\ngsilva\\Downloads\\1-datasets\\Clientes.csv\"),[Delimiter=\";\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}}),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Tipo Alterado\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"ID Cliente\", type text}, {\"Nome Cliente\", type text}, {\"Segmento\", type text}, {\"Cidade\", type text}, {\"Estado\", type text}, {\"Pais\", type text}, {\"Mercado\", type text}, {\"Regiao\", type text}})",
                "in",
                "    #\"Tipo Alterado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Pedidos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "ID Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97173685-fdff-4872-aeb6-9cfe81b48503",
            "sourceColumn": "ID Pedido",
            "summarizeBy": "none"
          },
          {
            "name": "Data Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b2730b13-8985-4ce8-9ca1-6a81c63abe5d",
            "sourceColumn": "Data Pedido",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_2f00db4d-7c5b-4fa3-b6fc-ae9547d2247c"
                },
                "isDefault": true,
                "relationship": "5327edaf-2a96-491f-a5cb-714bf0e8d6ef"
              }
            ]
          },
          {
            "name": "Data Envio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f387af79-9aa5-4728-ade9-67dea609ef13",
            "sourceColumn": "Data Envio",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_548a3cda-c5a8-44fa-ab34-87aa11109832"
                },
                "isDefault": true,
                "relationship": "8d4b3d60-a80e-4dc9-8795-69601627cdfd"
              }
            ]
          },
          {
            "name": "Modo Envio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6563047a-e138-42cf-98f6-9f0382958a16",
            "sourceColumn": "Modo Envio",
            "summarizeBy": "none"
          },
          {
            "name": "Prioridade Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d30dd9fc-3790-4b3c-9da5-007c930096fa",
            "sourceColumn": "Prioridade Pedido",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "84c60cff-8729-4553-a218-14eae60bba8b",
        "partitions": [
          {
            "name": "Pedidos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\ngsilva\\Downloads\\1-datasets\\Pedidos.csv\"),[Delimiter=\";\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"ID Pedido\", type text}, {\"Data Pedido\", type date}, {\"Data Envio\", type date}, {\"Modo Envio\", type text}, {\"Prioridade Pedido\", type text}}),",
                "    #\"Texto Aparado\" = Table.TransformColumns(#\"Tipo Alterado\",{{\"ID Pedido\", Text.Trim, type text}}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Texto Aparado\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_2ef3f08c-8524-4dcd-8244-52bdb2e533c2",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e91add86-dfe1-402d-bb00-05a43f479217",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "5b263021-938e-46bc-be95-7b8f9e735f87",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ef940b15-c1f6-472e-b7a2-975c21fbefd6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "79f66f71-d373-4d33-8d68-b3022e69f068",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "61a1cc63-77c8-4736-96d9-ad373db85349",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "53de6d6a-2418-4469-8253-7f932d3fd8a1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "bf037fb6-861a-413c-9b9e-230116874fab",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "4720a3dc-9c54-44ca-922b-848418607b10",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "2fd3d410-f1c4-44d2-a3db-da9b4e5788df",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "adc0f939-3d44-48e0-9808-6933c25f373f",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "bf0f00e6-1814-42fc-892c-e4fadf4d192e",
                "ordinal": 3
              }
            ],
            "lineageTag": "bd28d397-b083-42ec-8034-7510b1236176"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "21ff42de-c712-4ceb-8ea5-764cce4f6c3a",
        "partitions": [
          {
            "name": "DateTableTemplate_2ef3f08c-8524-4dcd-8244-52bdb2e533c2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2f00db4d-7c5b-4fa3-b6fc-ae9547d2247c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f21da503-964b-4c98-8bf3-f80fc78ac79d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "78f841b2-51f5-4b7c-8423-bff998a27966",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "aafba814-2442-4eca-82ad-12d35fcd8ce2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "deaf60e2-840a-4dc5-992f-a344704dedf3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "e1e1c6ac-f1a5-4035-a6e5-c8763218e05d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f2fab59f-48a3-40e1-96e0-aa58574806f2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "707f7d03-f621-43d0-94bc-c6cd4715f5d6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "e70981ed-08d9-43c3-a5d9-5e525b99bd7a",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "aa6aeba5-1481-4339-ad33-1b7903458fd0",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "a463573b-643b-4598-a0e5-33c048547c50",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "93e69fd0-5b5b-4848-8712-5a8699efbdf6",
                "ordinal": 3
              }
            ],
            "lineageTag": "b1304967-1163-4fa4-9789-441b80014440"
          }
        ],
        "isHidden": true,
        "lineageTag": "8573dccc-75fd-4b37-8ab4-4982e055d174",
        "partitions": [
          {
            "name": "LocalDateTable_2f00db4d-7c5b-4fa3-b6fc-ae9547d2247c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Pedidos'[Data Pedido])), 1, 1), Date(Year(MAX('Pedidos'[Data Pedido])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_548a3cda-c5a8-44fa-ab34-87aa11109832",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "50bb867e-5322-4dd2-a0aa-36768af4fc8b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "8584dd96-e12a-4aec-b56b-be3e67d85545",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "fda04fb7-c2ea-48f6-a508-110d7baa6c7f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "92479693-a3cb-47ba-8c48-8319511d325d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "540c52c7-0da4-4e31-b3ae-0881e747748b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "33f90959-c5ab-4740-aefe-13e532756321",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5afb13d8-2a14-4885-8edd-23e7403f7613",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "4e3ee700-5606-49be-83da-5eb7026bef17",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "ba91a6b9-38bf-4115-b9a0-f601e847352b",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "3368dc3c-92b8-4e79-817f-9d3dc4b6283d",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "97d524d9-b2bb-4e2b-8386-72c7e6d66da7",
                "ordinal": 3
              }
            ],
            "lineageTag": "e1ba32c1-ca2a-4e7f-bf77-55333c5246f4"
          }
        ],
        "isHidden": true,
        "lineageTag": "84b02e75-6bb2-44c3-821c-19dad0b3e554",
        "partitions": [
          {
            "name": "LocalDateTable_548a3cda-c5a8-44fa-ab34-87aa11109832",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Pedidos'[Data Envio])), 1, 1), Date(Year(MAX('Pedidos'[Data Envio])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Produtos",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "370fc423-75bc-4584-a035-c2777b1aecb9",
            "sourceColumn": "ID Produto",
            "summarizeBy": "none"
          },
          {
            "name": "Categoria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a58a157-35f2-4cc7-ada2-1f6d6d5203a7",
            "sourceColumn": "Categoria",
            "summarizeBy": "none"
          },
          {
            "name": "SubCategoria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "175de6b6-ea0e-497a-88ae-b6b88e9c54b0",
            "sourceColumn": "SubCategoria",
            "summarizeBy": "none"
          },
          {
            "name": "Nome Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5ac8ef4-d975-4acf-b0e3-4b303d4a8751",
            "sourceColumn": "Nome Produto",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "727021c2-b3f2-42fb-8a76-1ffe5df2f571",
        "partitions": [
          {
            "name": "Produtos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\ngsilva\\Downloads\\1-datasets\\Produtos.csv\"),[Delimiter=\";\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}}),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Tipo Alterado\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"ID Produto\", type text}, {\"Categoria\", type text}, {\"SubCategoria\", type text}, {\"Nome Produto\", type text}}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Tipo Alterado1\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Vendas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d637ee8-b3d3-49b0-b219-fcf857946b5e",
            "sourceColumn": "Pedido",
            "summarizeBy": "none"
          },
          {
            "name": "Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "233682e8-2fdc-4b97-9d3b-fcc768930d3b",
            "sourceColumn": "Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efb94ba8-8f68-4b9c-8c51-d0c972ea76d2",
            "sourceColumn": "Produto",
            "summarizeBy": "none"
          },
          {
            "name": "Valor Venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "48b76332-590b-4fe3-855d-eb84ffb835a9",
            "sourceColumn": "Valor Venda",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantidade Vendida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "836d7989-c0e0-4ee5-b55f-813d66dda6c4",
            "sourceColumn": "Quantidade Vendida",
            "summarizeBy": "sum"
          },
          {
            "name": "Custo Envio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b93ae62d-a0bb-4daf-bdf5-e08470b7ce2f",
            "sourceColumn": "Custo Envio",
            "summarizeBy": "sum"
          },
          {
            "name": "Lucro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "Vendas[Valor Venda] - Vendas[Custo Envio]",
            "isDataTypeInferred": true,
            "lineageTag": "692d198b-9c50-4f38-b97a-9f81c6910883",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Margem Lucro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "ROUND(DIVIDE(Vendas[Lucro], Vendas[Valor Venda]) * 100, 2)",
            "isDataTypeInferred": true,
            "lineageTag": "b34a03e2-94f7-47c3-ad05-5b93f7286fed",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "d5d1334a-7686-471f-8a2c-c1bdc117c2cd",
        "partitions": [
          {
            "name": "Vendas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\ngsilva\\Downloads\\1-datasets\\Vendas.csv\"),[Delimiter=\";\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Pedido\", type text}, {\"Cliente\", type text}, {\"Produto\", type text}, {\"Valor Venda\", type number}, {\"Quantidade Vendida\", Int64.Type}, {\"Custo Envio\", type number}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}